version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run: npm run install
      - run: npm run build
      - run:
          name: Store Artifacts
          command: |
            echo frontend/dist > /tmp/artifacts;