name: Build Pipeline

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install & Build
      run: |
        npm install
        npm run build
