name: Unit Tests
on: [push]

jobs:
  test:
    
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v2
      - name: Add missing Config-Files.
        run: |
          cd ./backend/db/
          echo '{ "host": "", "user": "", "password": "", "database": "" }' > config.json
          cd ../discord/
          echo '{ "token": "", "prefix": "", "server": "", "raidLeadRole": "" }' > config.json
          cd ../gw2api/
          echo '{ "keyRL": "" }' > key.json
          cd ../mailer
          echo '{ "host": "", "auth": { "user": "", "pass": "" } }' > config.json

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run build:models --if-present
      - run: npm run test:ci
