name: Unit Tests
on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        modules: ['backend']
        
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: cd ${{ matrix.modules }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
